---
# yamllint disable line-length
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Tag
        uses: codfish/semantic-release-action@v3
        id: semantic
        with:
          branches: |
            [
              'main'
            ]
          additional-packages: |
            [
              'conventional-changelog-conventionalcommits'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
