---
name: Test Languages

on:
  pull_request:

jobs:
  build:
    name: Test Languages
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Build test image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: .github/workflows/test-langauges.dockerfile
          tags: test-image:latest
          push: false
      -
        name: Test Languages
        uses: addnab/docker-run-action@v3
        with:
          image: test-image:latest
          run: /bin/bash -c "source ~/.bashrc && /languages/bin/test.bash"
